using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using BuildingBlocks.Application.Security;
using FluentAssertions;
using Master.Domain.Tenants;
using Master.Infrastructure.Services;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;

namespace UnitTests.Backend.Security;

/// <summary>
/// Unit tests for <see cref="JwtImpersonationTokenService"/>.
/// </summary>
public sealed class JwtImpersonationTokenServiceTests
{
    private readonly ImpersonationJwtOptions _defaultOptions = new()
    {
        Issuer = "AdMetricsPro.Master.Test",
        Audience = "AdMetricsPro.Tenants.Test",
        SecretKey = "SuperSecretTestKeyThatIsLongEnoughToSatisfySha256Requirements!",
        DefaultExpirationMinutes = 30
    };

    private JwtImpersonationTokenService CreateService(ImpersonationJwtOptions? options = null)
    {
        var opt = Options.Create(options ?? _defaultOptions);
        return new JwtImpersonationTokenService(opt);
    }

    /// <summary>
    /// Verifies that GenerateToken creates a JWT with all required contextual claims.
    /// </summary>
    [Fact]
    public void GenerateToken_ShouldIncludeAllMandatoryImpersonationClaims()
    {
        // Arrange
        var service = CreateService();
        var tenant = Tenant.Create("Beta Inc", "11222333000181", "beta").Value;
        var superAdminId = Guid.NewGuid();
        var session = ImpersonationSession.Create(
            tenant.Id,
            superAdminId,
            "INC-77777",
            "Suporte técnico emergencial para conferência de métricas",
            40,
            DateTime.UtcNow).Value;

        // Act
        var result = service.GenerateToken(session, tenant);

        // Assert
        result.IsSuccess.Should().BeTrue();
        var tokenHandler = new JwtSecurityTokenHandler();
        var jwt = tokenHandler.ReadJwtToken(result.Value);

        jwt.Issuer.Should().Be(_defaultOptions.Issuer);
        jwt.Audiences.Should().Contain(_defaultOptions.Audience);

        jwt.Claims.Should().Contain(c => c.Type == ImpersonationClaims.IsImpersonated && c.Value == "true");
        jwt.Claims.Should().Contain(c => c.Type == ImpersonationClaims.OriginalSuperAdminId && c.Value == superAdminId.ToString());
        jwt.Claims.Should().Contain(c => c.Type == ImpersonationClaims.TenantId && c.Value == tenant.Id.Value.ToString());
        jwt.Claims.Should().Contain(c => c.Type == ImpersonationClaims.SupportTicketId && c.Value == "INC-77777");
        jwt.Claims.Should().Contain(c => c.Type == ImpersonationClaims.SessionId && c.Value == session.Id.ToString());
        jwt.Claims.Should().Contain(c => c.Type == JwtRegisteredClaimNames.Sub && c.Value == superAdminId.ToString());
    }

    /// <summary>
    /// Verifies that ValidateToken returns a valid ClaimsPrincipal for a token generated by the service.
    /// </summary>
    [Fact]
    public void ValidateToken_ShouldReturnClaimsPrincipal_WhenTokenIsValid()
    {
        // Arrange
        var service = CreateService();
        var tenant = Tenant.Create("Beta Inc", "11222333000181", "beta").Value;
        var superAdminId = Guid.NewGuid();
        var session = ImpersonationSession.Create(
            tenant.Id,
            superAdminId,
            "INC-88888",
            "Investigação de relatório divergente",
            30,
            DateTime.UtcNow).Value;

        var token = service.GenerateToken(session, tenant).Value;

        // Act
        var validationResult = service.ValidateToken(token);

        // Assert
        validationResult.IsSuccess.Should().BeTrue();
        var principal = validationResult.Value;

        principal.FindFirst(ImpersonationClaims.IsImpersonated)?.Value.Should().Be("true");
        principal.FindFirst(ImpersonationClaims.TenantId)?.Value.Should().Be(tenant.Id.Value.ToString());
        principal.FindFirst(ImpersonationClaims.OriginalSuperAdminId)?.Value.Should().Be(superAdminId.ToString());
        principal.FindFirst(ImpersonationClaims.SupportTicketId)?.Value.Should().Be("INC-88888");
        principal.FindFirst(ImpersonationClaims.SessionId)?.Value.Should().Be(session.Id.ToString());
    }

    /// <summary>
    /// Verifies that ValidateToken returns failure when signature is tampered.
    /// </summary>
    [Fact]
    public void ValidateToken_ShouldReturnFailure_WhenSignatureIsTampered()
    {
        // Arrange
        var service = CreateService();
        var tenant = Tenant.Create("Beta Inc", "11222333000181", "beta").Value;
        var session = ImpersonationSession.Create(
            tenant.Id,
            Guid.NewGuid(),
            "INC-12345",
            "Investigação de suporte técnico",
            30,
            DateTime.UtcNow).Value;

        var token = service.GenerateToken(session, tenant).Value;
        var parts = token.Split('.');
        var tamperedPayload = parts[1] + "tampered";
        var tamperedToken = $"{parts[0]}.{tamperedPayload}.{parts[2]}";

        // Act
        var result = service.ValidateToken(tamperedToken);

        // Assert
        result.IsFailure.Should().BeTrue();
        result.Error.Code.Should().Be("ImpersonationToken.Invalid");
    }

    /// <summary>
    /// Verifies that ValidateToken returns failure when token is expired.
    /// </summary>
    [Fact]
    public void ValidateToken_ShouldReturnFailure_WhenTokenIsExpired()
    {
        // Arrange
        var service = CreateService();
        var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_defaultOptions.SecretKey));
        var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256);

        var claims = new[]
        {
            new Claim(ImpersonationClaims.IsImpersonated, "true"),
            new Claim(ImpersonationClaims.OriginalSuperAdminId, Guid.NewGuid().ToString()),
            new Claim(ImpersonationClaims.TenantId, Guid.NewGuid().ToString()),
            new Claim(ImpersonationClaims.SupportTicketId, "INC-99999"),
            new Claim(ImpersonationClaims.SessionId, Guid.NewGuid().ToString())
        };

        var expiredTokenDescriptor = new JwtSecurityToken(
            issuer: _defaultOptions.Issuer,
            audience: _defaultOptions.Audience,
            claims: claims,
            notBefore: DateTime.UtcNow.AddMinutes(-60),
            expires: DateTime.UtcNow.AddMinutes(-10),
            signingCredentials: credentials);

        var expiredTokenString = new JwtSecurityTokenHandler().WriteToken(expiredTokenDescriptor);

        // Act
        var result = service.ValidateToken(expiredTokenString);

        // Assert
        result.IsFailure.Should().BeTrue();
        result.Error.Code.Should().Be("ImpersonationToken.Expired");
    }

    /// <summary>
    /// Verifies that ValidateToken returns failure when token does not carry impersonation claims.
    /// </summary>
    [Fact]
    public void ValidateToken_ShouldReturnFailure_WhenTokenLacksImpersonationClaims()
    {
        // Arrange
        var service = CreateService();
        var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_defaultOptions.SecretKey));
        var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256);

        // Regular user token without impersonation claims
        var regularClaims = new[]
        {
            new Claim(JwtRegisteredClaimNames.Sub, Guid.NewGuid().ToString()),
            new Claim(ClaimTypes.Role, "StandardUser")
        };

        var tokenDescriptor = new JwtSecurityToken(
            issuer: _defaultOptions.Issuer,
            audience: _defaultOptions.Audience,
            claims: regularClaims,
            notBefore: DateTime.UtcNow,
            expires: DateTime.UtcNow.AddMinutes(30),
            signingCredentials: credentials);

        var tokenString = new JwtSecurityTokenHandler().WriteToken(tokenDescriptor);

        // Act
        var result = service.ValidateToken(tokenString);

        // Assert
        result.IsFailure.Should().BeTrue();
        result.Error.Code.Should().Be("ImpersonationToken.NotImpersonated");
    }
}
