// <auto-generated />
using System;
using Master.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Master.Infrastructure.Persistence.Migrations.MasterCatalog;

[DbContext(typeof(MasterDbContext))]
[Migration("20260903180000_Add_ApiHealthAndQuotaTracking")]
partial class Add_ApiHealthAndQuotaTracking
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Master.Domain.Auditing.MasterAuditEntry", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Details")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<Guid?>("ImpersonationSessionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("IpAddress")
                    .HasMaxLength(45)
                    .HasColumnType("nvarchar(45)");

                b.Property<bool>("IsImpersonated")
                    .HasColumnType("bit");

                b.Property<string>("Resource")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ResourceId")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<Guid?>("SuperAdminId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("SupportTicketId")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Tags")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("Action");

                b.HasIndex("IsImpersonated", "CreatedAtUtc");

                b.HasIndex("SuperAdminId", "CreatedAtUtc");

                b.HasIndex("TenantId", "CreatedAtUtc");

                b.ToTable("MasterAuditLogs", (string)null);
            });

        modelBuilder.Entity("Master.Domain.Integrations.ApiQuotaTracker", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AlertLevel")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<double>("CriticalThresholdPercentage")
                    .HasColumnType("float");

                b.Property<long>("CurrentConsumption")
                    .HasColumnType("bigint");

                b.Property<DateTime>("LastUpdatedUtc")
                    .HasColumnType("datetime2");

                b.Property<long>("MaxLimit")
                    .HasColumnType("bigint");

                b.Property<string>("Platform")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<double>("WarningThresholdPercentage")
                    .HasColumnType("float");

                b.Property<TimeSpan>("WindowDuration")
                    .HasColumnType("time");

                b.Property<DateTime>("WindowStartUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("Platform")
                    .IsUnique();

                b.ToTable("ApiQuotaTrackers", (string)null);
            });

        modelBuilder.Entity("Master.Domain.Integrations.TenantApiConnection", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AccountIdentifier")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("AccountName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("ErrorMessage")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<DateTime?>("LastSyncAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Platform")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("TenantName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime?>("TokenExpiresAtUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("Status", "Platform");

                b.HasIndex("TenantId", "Platform");

                b.ToTable("TenantApiConnections", (string)null);
            });

        modelBuilder.Entity("Master.Domain.Plans.SubscriptionPlan", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("AnnualDiscountPercentage")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<decimal>("MonthlyPrice")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Tier")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("SubscriptionPlans", (string)null);
            });

        modelBuilder.Entity("Master.Domain.Tenants.ImpersonationSession", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("ExpiresAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("RevokeReason")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime?>("RevokedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<Guid>("SuperAdminId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("SupportTicketId")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("SuperAdminId");

                b.HasIndex("SupportTicketId");

                b.HasIndex("TenantId");

                b.ToTable("ImpersonationSessions", (string)null);
            });

        modelBuilder.Entity("Master.Domain.Tenants.Tenant", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Cnpj")
                    .IsRequired()
                    .HasMaxLength(18)
                    .HasColumnType("nvarchar(18)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("CustomDomain")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("DatabaseConnectionString")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("DatabaseName")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("DunningStage")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)")
                    .HasDefaultValue("None");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime?>("PaymentDueDateUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("Subdomain")
                    .IsRequired()
                    .HasMaxLength(63)
                    .HasColumnType("nvarchar(63)");

                b.Property<DateTime?>("SuspendedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("SuspensionReason")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("Cnpj")
                    .IsUnique();

                b.HasIndex("CustomDomain")
                    .IsUnique()
                    .HasFilter("[CustomDomain] IS NOT NULL");

                b.HasIndex("Subdomain")
                    .IsUnique();

                b.ToTable("Tenants", (string)null);
            });

        modelBuilder.Entity("Master.Domain.Plans.SubscriptionPlan", b =>
            {
                b.OwnsOne("Master.Domain.Plans.PlanFeatures", "Features", b1 =>
                    {
                        b1.Property<Guid>("SubscriptionPlanId")
                            .HasColumnType("uniqueidentifier");

                        b1.Property<bool>("HasAiCopilot")
                            .HasColumnType("bit")
                            .HasColumnName("HasAiCopilot");

                        b1.Property<bool>("HasCrossNetworkAutomations")
                            .HasColumnType("bit")
                            .HasColumnName("HasCrossNetworkAutomations");

                        b1.Property<bool>("HasCustomCname")
                            .HasColumnType("bit")
                            .HasColumnName("HasCustomCname");

                        b1.Property<bool>("HasWhiteLabel")
                            .HasColumnType("bit")
                            .HasColumnName("HasWhiteLabel");

                        b1.HasKey("SubscriptionPlanId");

                        b1.ToTable("SubscriptionPlans");

                        b1.WithOwner()
                            .HasForeignKey("SubscriptionPlanId");
                    });

                b.OwnsOne("Master.Domain.Plans.PlanLimits", "Limits", b1 =>
                    {
                        b1.Property<Guid>("SubscriptionPlanId")
                            .HasColumnType("uniqueidentifier");

                        b1.Property<int>("MaxSeats")
                            .HasColumnType("int")
                            .HasColumnName("MaxSeats");

                        b1.Property<int>("MaxWorkspaces")
                            .HasColumnType("int")
                            .HasColumnName("MaxWorkspaces");

                        b1.Property<decimal>("MonthlyAdSpendCap")
                            .HasPrecision(18, 2)
                            .HasColumnType("decimal(18,2)")
                            .HasColumnName("MonthlyAdSpendCap");

                        b1.HasKey("SubscriptionPlanId");

                        b1.ToTable("SubscriptionPlans");

                        b1.WithOwner()
                            .HasForeignKey("SubscriptionPlanId");
                    });

                b.Navigation("Features")
                    .IsRequired();

                b.Navigation("Limits")
                    .IsRequired();
            });

        modelBuilder.Entity("Master.Domain.Tenants.ImpersonationSession", b =>
            {
                b.HasOne("Master.Domain.Tenants.Tenant", null)
                    .WithMany()
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
