// <auto-generated />
using System;
using Master.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Master.Infrastructure.Persistence.Migrations.MasterCatalog;

[DbContext(typeof(MasterDbContext))]
[Migration("20260903130000_Add_SubscriptionPlans")]
partial class Add_SubscriptionPlans
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Master.Domain.Plans.SubscriptionPlan", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("AnnualDiscountPercentage")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<decimal>("MonthlyPrice")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Tier")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("SubscriptionPlans", (string)null);
            });

        modelBuilder.Entity("Master.Domain.Tenants.Tenant", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Cnpj")
                    .IsRequired()
                    .HasMaxLength(14)
                    .HasColumnType("nvarchar(14)");

                b.Property<string>("CompanyName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("EncryptedConnectionString")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<DateTime?>("SubscriptionExpiresAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Subdomain")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("nvarchar(80)");

                b.Property<string>("Tier")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.HasKey("Id");

                b.HasIndex("Cnpj")
                    .IsUnique();

                b.HasIndex("Subdomain")
                    .IsUnique();

                b.ToTable("Tenants", (string)null);
            });

        modelBuilder.Entity("Master.Domain.Plans.SubscriptionPlan", b =>
            {
                b.OwnsOne("Master.Domain.Plans.PlanFeatures", "Features", b1 =>
                    {
                        b1.Property<Guid>("SubscriptionPlanId")
                            .HasColumnType("uniqueidentifier");

                        b1.Property<bool>("HasAiCopilot")
                            .HasColumnType("bit")
                            .HasColumnName("HasAiCopilot");

                        b1.Property<bool>("HasCrossNetworkAutomations")
                            .HasColumnType("bit")
                            .HasColumnName("HasCrossNetworkAutomations");

                        b1.Property<bool>("HasCustomCname")
                            .HasColumnType("bit")
                            .HasColumnName("HasCustomCname");

                        b1.Property<bool>("HasWhiteLabel")
                            .HasColumnType("bit")
                            .HasColumnName("HasWhiteLabel");

                        b1.HasKey("SubscriptionPlanId");

                        b1.ToTable("SubscriptionPlans");

                        b1.WithOwner()
                            .HasForeignKey("SubscriptionPlanId");
                    });

                b.OwnsOne("Master.Domain.Plans.PlanLimits", "Limits", b1 =>
                    {
                        b1.Property<Guid>("SubscriptionPlanId")
                            .HasColumnType("uniqueidentifier");

                        b1.Property<int>("MaxSeats")
                            .HasColumnType("int")
                            .HasColumnName("MaxSeats");

                        b1.Property<int>("MaxWorkspaces")
                            .HasColumnType("int")
                            .HasColumnName("MaxWorkspaces");

                        b1.Property<decimal>("MonthlyAdSpendCap")
                            .HasPrecision(18, 2)
                            .HasColumnType("decimal(18,2)")
                            .HasColumnName("MonthlyAdSpendCap");

                        b1.HasKey("SubscriptionPlanId");

                        b1.ToTable("SubscriptionPlans");

                        b1.WithOwner()
                            .HasForeignKey("SubscriptionPlanId");
                    });

                b.Navigation("Features")
                    .IsRequired();

                b.Navigation("Limits")
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
