// <auto-generated />
using System;
using Master.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Master.Infrastructure.Persistence.Migrations.TenantOperational;

[DbContext(typeof(TenantOperationalDbContext))]
[Migration("20260915180000_Add_OAuthTokenVaults_Table")]
partial class Add_OAuthTokenVaults_Table
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("BuildingBlocks.Domain.Integrations.OAuthTokenVault", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("AccessTokenExpiresAtUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("EncryptedAccessToken")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("EncryptedRefreshToken")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ExternalAccountId")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("ExternalAccountName")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.Property<string>("Platform")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime?>("RefreshTokenExpiresAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Scopes")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)")
                    .HasDefaultValue("");

                b.Property<string>("Status")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Active");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<Guid>("WorkspaceId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("WorkspaceId", "Platform")
                    .IsUnique();

                b.ToTable("OAuthTokenVaults", (string)null);
            });

        modelBuilder.Entity("BuildingBlocks.Domain.Tenants.ConnectedAdAccount", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AccountName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Currency")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)")
                    .HasDefaultValue("BRL");

                b.Property<string>("ExternalAccountId")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<bool>("IsDemo")
                    .HasColumnType("bit");

                b.Property<string>("Platform")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Status")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("Connected");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<Guid>("WorkspaceId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("IsDemo");

                b.HasIndex("WorkspaceId");

                b.HasIndex("WorkspaceId", "Platform");

                b.ToTable("ConnectedAdAccounts", (string)null);
            });

        modelBuilder.Entity("BuildingBlocks.Domain.Tenants.Squad", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("IsActive");

                b.HasIndex("Name");

                b.ToTable("Squads", (string)null);
            });

        modelBuilder.Entity("BuildingBlocks.Domain.Tenants.SquadMember", b =>
            {
                b.Property<Guid>("SquadId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("TenantUserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("JoinedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("SquadId", "TenantUserId");

                b.ToTable("SquadMembers", (string)null);
            });

        modelBuilder.Entity("BuildingBlocks.Domain.Tenants.SquadWorkspace", b =>
            {
                b.Property<Guid>("SquadId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("WorkspaceId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("AssignedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("SquadId", "WorkspaceId");

                b.ToTable("SquadWorkspaces", (string)null);
            });

        modelBuilder.Entity("BuildingBlocks.Domain.Tenants.TenantAuditLog", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Details")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<string>("IpAddress")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Resource")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("CreatedAtUtc");

                b.HasIndex("TenantId");

                b.HasIndex("UserId");

                b.ToTable("TenantAuditLogs", (string)null);
            });

        modelBuilder.Entity("BuildingBlocks.Domain.Tenants.TenantBranding", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("DarkLogoUrl")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("FaviconUrl")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("LightLogoUrl")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("PrimaryColor")
                    .IsRequired()
                    .HasMaxLength(9)
                    .HasColumnType("nvarchar(9)");

                b.Property<string>("SecondaryColor")
                    .IsRequired()
                    .HasMaxLength(9)
                    .HasColumnType("nvarchar(9)");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .IsUnique();

                b.ToTable("TenantBranding", (string)null);
            });

        modelBuilder.Entity("BuildingBlocks.Domain.Tenants.TenantUser", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.HasIndex("TenantId");

                b.ToTable("TenantUsers", (string)null);
            });

        modelBuilder.Entity("BuildingBlocks.Domain.Tenants.Workspace", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ClientName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("CnpjOrCpf")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("MonthlyBudget")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Segment")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("CnpjOrCpf");

                b.HasIndex("IsActive");

                b.ToTable("Workspaces", (string)null);
            });

        modelBuilder.Entity("BuildingBlocks.Domain.Tenants.SquadMember", b =>
            {
                b.HasOne("BuildingBlocks.Domain.Tenants.Squad", null)
                    .WithMany("Members")
                    .HasForeignKey("SquadId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("BuildingBlocks.Domain.Tenants.SquadWorkspace", b =>
            {
                b.HasOne("BuildingBlocks.Domain.Tenants.Squad", null)
                    .WithMany("Workspaces")
                    .HasForeignKey("SquadId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.TenantSchemaMarker", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("Id");

                b.ToTable("TenantSchemaMarkers", (string)null);
            });
#pragma warning restore 612, 618
    }
}
